# Generated by Django 3.2.7 on 2023-12-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='static/post_images/'),
        ),
        migrations.AlterField(
            model_name='pdf',
            name='pdf',
            field=models.FileField(upload_to='static/post_pdfs/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='static/post_videos/'),
        ),
    ]
